version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - node-exporter
      - mikrotik-exporter

  grafana:
    image: grafana/grafana:8.5.0
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "P@ssw0rd"  # Установите ваш пароль
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node-exporter
    ports:
      - "9101:9100"  # Изменили порт, чтобы избежать конфликта (хост:порт контейнера)
    networks:
      - monitoring

  mikrotik-exporter:
    image: vitalidze/mikrotik-exporter
    container_name: mikrotik-exporter
    environment:
      - ROUTER_API_HOST=192.168.65.2      # IP адрес устройства MikroTik
      - ROUTER_API_PORT=8728              # Порт API MikroTik (по умолчанию 8728)
      - ROUTER_API_USER=admin             # Имя пользователя для подключения
      - ROUTER_API_PASSWORD=12345678 # Пароль для подключения
    ports:
      - "9102:9100"  # Изменили порт, чтобы избежать конфликта (хост:порт контейнера)
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
