global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter_second'
    static_configs:
      - targets:
        - 'Second-SRV:9100'  # IP-адрес и порт Node Exporter на Second-SRV

scrape_configs:
  - job_name: 'node_exporter_first'
    static_configs:
      - targets:
          - 'localhost:9101'  # Порт для Node Exporter на хосте

  - job_name: 'mikrotik'
    static_configs:
      - targets:
          - 'localhost:9102'  # Порт для MikroTik Exporter на хосте
