global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter_second'
    static_configs:
      - targets:
        - '192.168.67.3:9100'  # IP-адрес и порт Node Exporter на Second-SRV

  - job_name: 'node_exporter_first'
    static_configs:
      - targets:
          - '192.168.65.3:9101'  # Порт для Node Exporter на хосте

  - job_name: 'mktxp'
    static_configs:
      - targets: ['mktxp:49090']