version: '2'

networks:
  macvlan_1:
    driver: macvlan
    driver_opts:
      parent: enp0s3
    ipam:
      config:
        - subnet: 192.168.67.0/24
          gateway: 192.168.67.2

volumes:
  twnextcloud:
  db:

services:
  db:
    image: mysql
    restart: unless-stopped
    volumes:
      - /opt:/opt
      - db:/var/lib/mysql
    networks:
      macvlan_1:
        ipv4_address: 192.168.67.4
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: unless-stopped
    ports:
      - "8081:80"
    links:
      - db
    networks:
      macvlan_1:
        ipv4_address: 192.168.67.5
    volumes:
      - /opt:/opt
      - twnextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db